### ISSUE TITLE
Build error in object_detection_ssd_model, object_detection_yolov2voc_model and face_reidentification_model

### ISSUE THREAD

**Issue by Corsair-cxs** [intel/ros_openvino_toolkit#116]
### Version
dev-ov2020.3

### Reproduction link
1. https://github.com/intel/ros_openvino_toolkit/blob/dev-ov2020.3/dynamic_vino_lib/src/models/object_detection_ssd_model.cpp
2. https://github.com/intel/ros_openvino_toolkit/blob/dev-ov2020.3/dynamic_vino_lib/src/models/object_detection_yolov2voc_model.cpp
3. https://github.com/intel/ros_openvino_toolkit/blob/dev-ov2020.3/dynamic_vino_lib/src/models/face_reidentification_model.cpp
4. https://github.com/intel/ros_openvino_toolkit/blob/dev-ov2020.3/dynamic_vino_lib/src/pipeline_manager.cpp
5. https://github.com/intel/ros_openvino_toolkit/blob/dev-ov2020.3/dynamic_vino_lib/CMakeLists.txt

### Steps to reproduce
run `catkin_make` in catkin_ws workspace.

### What is expected?
May be it was caused by OpenVINO version update and such API was modified. May be we should modify our code refer to OpenVINO source code.

### What is actually happening?
When I tried to build projects, it's shown in console:
```
error: invalid use of incomplete type ‘using element_type = class Engines::Engine {aka class Engines::Engine}’
   InferenceEngine::Blob::Ptr input_blob = engine->getRequest()->GetBlob(input_name);
```

While I commented out the code related in such modules, the error was not in display.
```
object_detection_ssd_model
object_detection_yolov2voc_model
face_reidentification_model
```

**Comment by LewisLiuPub** [comment]
agree to disable the inf features during the first porting phase.
