### ISSUE TITLE
enable object_detection_ssd_model

### ISSUE THREAD

**Issue by Corsair-cxs** [intel/ros_openvino_toolkit#147]
### Version
dev-ov2020.3

### Reproduction link
https://github.com/intel/ros_openvino_toolkit/blob/dev-ov2020.3/dynamic_vino_lib/CMakeLists.txt
https://github.com/intel/ros_openvino_toolkit/blob/dev-ov2020.3/dynamic_vino_lib/include/dynamic_vino_lib/models/object_detection_ssd_model.h
https://github.com/intel/ros_openvino_toolkit/blob/dev-ov2020.3/dynamic_vino_lib/src/pipeline_manager.cpp 

### Steps to reproduce
run `catkin_make` in catkin_ws workspace.

### What is expected?
Model `object_detection_ssd_model` shoule be enabled in our project.

### What is actually happening?
When I launch `pipeline_object.launch`, it seems that model was not loaded yet.

**Comment by LewisLiuPub** [comment]
#149 , #150 , #150  these PRs fix this issue.
