### ISSUE TITLE
2021.4 Inference Engine Incompatibility issue in CMake

### ISSUE THREAD

**Issue by sreshu** [intel/ros_openvino_toolkit#179]
By not providing "FindInferenceEngine.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "InferenceEngine", but CMake did not find one.

  Could not find a package configuration file provided by "InferenceEngine"
  (requested version 1.5) with any of the following names:

    InferenceEngineConfig.cmake
    inferenceengine-config.cmake

  Add the installation prefix of "InferenceEngine" to CMAKE_PREFIX_PATH or
  set "InferenceEngine_DIR" to a directory containing one of the above files.
  If "InferenceEngine" provides a separate development package or SDK, be
  sure it has been installed.

**Comment by LewisLiuPub** [comment]
probably you need to `source` the OpenVINO scripts for env setup.

```bash
source <path/of/openvino/installation/folder>/bin/setupvars.sh
```

**Comment by sreshu** [comment]
Resolved! Had to put the latest OpenVino version 2.0 in the CMakelist
