### ISSUE TITLE
Missing message file in 2021 dev version

### ISSUE THREAD

**Issue by sreshu** [intel/ros_openvino_toolkit#184]
fatal error: vino_people_msgs/Emotion.h: No such file or directory
 #include <vino_people_msgs/Emotion.h>

**Comment by LewisLiuPub** [comment]
suppose vino_people_msgs is not depended by vino_core_lib, so it is not built before vino_core_lib. Could you please make clean and build again. If you also meet the error, please let me know more error logs.

**Comment by LewisLiuPub** [comment]
source code is updated to support new versions of ROS and OpenVINO. Main features have been tested.
I'll close this issue, please reopen it if you still meet the error.
