### ISSUE TITLE
ubuntu 20.04

### ISSUE THREAD

**Issue by chang556** [intel/ros_openvino_toolkit#193]
您好，請問ubuntu20.04，此功能包有支援嗎

**Comment by LewisLiuPub** [comment]
Yes, you can try the branch [melodic](https://github.com/intel/ros_openvino_toolkit/tree/melodic).

**Comment by chang556** [comment]
noetic can?

從我的iPhone傳送

> Lewis Liu ***@***.***> 於 2022年9月5日 上午8:39 寫道：
> 
> Yes, you can try the branch melodic.
> 
> —
> Rep

**Comment by LewisLiuPub** [comment]
Yes, see this guideline: https://github.com/intel/ros_openvino_toolkit/blob/master/doc/quick_start/getting_started_with_Noetic_Ubuntu20.04.md

**Comment by chang556** [comment]
thank you your help

**Comment by chang556** [comment]
Thank your help 👍

從我的iPhone傳送
