### ISSUE TITLE
Does 'Person Reidentification' need RGB stream?

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_openvino_toolkit#38]
I was a bit curious to know if the Person Reidentification needed a RGB stream to work or would it work on a grayscale image?

**Comment by houk-intel** [comment]
We only suport RGB stream so far.

**How The Reidentification Works**

The reidentification feature works by connecting the two models in series, see the [yaml file](https://github.com/intel/ros_openvino_toolkit/blob/master/vino_launch/param/pipeline_reidentification.yaml)
- person-detection-retail-0013: Detect persons from camera.

- person-reidentification-retail-0076: Form a vector of features for each detected person to decide whether it is a already detected one.

**About The Reidentification Model** 
The details about the person-reidentification-retail-0076 model is shown [here](https://github.com/opencv/open_model_zoo/blob/master/intel_models/person-reidentification-retail-0076/description/person-reidentification-retail-0076.md).
