### ISSUE TITLE
catkin_make error with ros_openvino

### ISSUE THREAD

**Issue by HermanLiu1** [intel/ros_openvino_toolkit#75]
I am trying to build the package. I have followed the guide but unfortunately I encounter a build error： **return-statement with no value, in function returning ‘void’ [-fpermissive].**
I am using **Tarball openVINO R3.1 2019 and the master branch** from this project.The **pipeline_object.launch can start** normally.

> [  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target tf_generate_messages_nodejs
[  0%] Built target diagnostic_msgs_generate_messages_eus
[  0%] Built target _catkin_empty_exported_target
[  0%] Built target diagnostic_msgs_generate_messages_nodejs
[  0%] Built target dynamic_reconfigure_gencfg
[  0%] Built target dynamic_reconfigure_generate_messages_py
[  0%] Built target _object_msgs_generate_messages_check_deps_DetectObject
[  0%] Built target dynamic_reconfigure_generate_messages_lisp
[  0%] Built target _object_msgs_generate_messages_check_deps_ObjectsInBoxes
[  0%] Built target _object_msgs_generate_messages_check_deps_Object
[  0%] Built target dynamic_reconfigure_generate_messages_nodejs
[  0%] Built target _object_msgs_generate_messages_check_deps_Objects
[  0%] Built target _object_msgs_generate_messages_check_deps_ObjectInBox
[  0%] Built target _object_msgs_generate_messages_check_deps_ClassifyObject
[  0%] Built target diagnostic_msgs_generate_messages_lisp
[  0%] Built target dynamic_reconfigure_generate_messages_eus
[  0%] Built target tf2_msgs_generate_messages_eus
[  0%] Built target tf2_msgs_generate_messages_nodejs
[  0%] Built target tf2_msgs_generate_messages_lisp
[  0%] Built target dynamic_reconfigure_generate_messages_cpp
[  0%] Built target tf2_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target actionlib_generate_messages_eus
[  0%] Built target actionlib_generate_messages_py
[  0%] Built target tf2_msgs_generate_messages_cpp
[  0%] Built target actionlib_generate_messages_nodejs
[  0%] Built target bond_generate_messages_eus
[  0%] Built target nav_msgs_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target tf_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_py
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target bond_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target tf_generate_messages_py
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target nav_msgs_generate_messages_py
[  0%] Built target nav_msgs_generate_messages_eus
[  0%] Built target actionlib_msgs_generate_messages_lisp
[  0%] Built target diagnostic_msgs_generate_messages_cpp
[  0%] Built target _realsense2_camera_generate_messages_check_deps_Extrinsics
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target nav_msgs_generate_messages_nodejs
[  0%] Built target _realsense2_camera_generate_messages_check_deps_IMUInfo
[  0%] Built target actionlib_msgs_generate_messages_cpp
[  0%] Built target nav_msgs_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target tf_generate_messages_eus
[  0%] Built target bond_generate_messages_cpp
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_eus
[  0%] Built target diagnostic_msgs_generate_messages_py
[  0%] Built target nodelet_generate_messages_lisp
[  0%] Built target actionlib_generate_messages_cpp
[  0%] Built target nodelet_generate_messages_eus
[  0%] Built target tf_generate_messages_cpp
[  0%] Built target nodelet_generate_messages_nodejs
[  0%] Built target nodelet_generate_messages_py
[  0%] Built target bond_generate_messages_nodejs
[  0%] Built target actionlib_generate_messages_lisp
[  0%] Built target nodelet_generate_messages_cpp
[  0%] Built target bond_generate_messages_py
[  1%] Built target realsense2_camera_generate_messages_py
[  2%] Built target realsense2_camera_generate_messages_eus
[  4%] Built target realsense2_camera_generate_messages_nodejs
[  4%] Built target realsense2_camera_generate_messages_lisp
[  4%] Built target vino_param_lib
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_AgeGenderSrv
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_AgeGenderStamped
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_PeopleSrv
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_ObjectsInMasks
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_ReidentificationSrv
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_HeadPoseSrv
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_HeadPose
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_ObjectsInMasksSrv
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_Emotion
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_HeadPoseStamped
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_PersonsStamped
[  4%] Built target _vino_people_msgs_generate_messages_check_deps_EmotionSrv
[  8%] Built target object_msgs_generate_messages_py
[  9%] Built target image_geometry
[ 12%] Built target object_msgs_generate_messages_nodejs
[ 13%] Built target cv_bridge
[ 16%] Built target object_msgs_generate_messages_lisp
[ 16%] Built target _vino_people_msgs_generate_messages_check_deps_EmotionsStamped
[ 20%] Built target object_msgs_generate_messages_eus
[ 20%] Built target _vino_people_msgs_generate_messages_check_deps_ReidentificationStamped
[ 22%] Built target object_msgs_generate_messages_cpp
[ 22%] Built target _vino_people_msgs_generate_messages_check_deps_Reidentification
[ 22%] Built target _vino_people_msgs_generate_messages_check_deps_AgeGender
[ 22%] Built target _vino_people_msgs_generate_messages_check_deps_ObjectInMask
[ 24%] Built target realsense2_camera_generate_messages_cpp
[ 24%] Built target object_msgs_generate_messages
[ 25%] Building CXX object vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/module_opencv4.cpp.o
[ 25%] Building CXX object vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/module.cpp.o
[ 25%] Built target realsense2_camera_generate_messages
[ 34%] Built target vino_people_msgs_generate_messages_cpp
[ 50%] Built target vino_people_msgs_generate_messages_nodejs
[ 56%] Built target vino_people_msgs_generate_messages_py
[ 61%] Built target vino_people_msgs_generate_messages_lisp
[ 70%] Built target vino_people_msgs_generate_messages_eus
[ 73%] Built target realsense2_camera
[ 73%] Built target vino_people_msgs_generate_messages
[ 90%] Built target vino_core_lib
[ 92%] Built target image_people_client
[ 92%] Built target image_object_client
[ 92%] Built target image_segmentation_client
[ 94%] Built target image_reidentification_client
[ 94%] Built target image_segmentation_server
[ 96%] Built target image_people_server
[ 97%] Built target image_object_server
[ 98%] Built target image_reidentification_server
[100%] Built target pipeline_with_params
In file included from /usr/include/python2.7/numpy/ndarrayobject.h:27:0,
                 from /home/ysxt001/openvino_ws/src/vision_opencv/cv_bridge/src/module.hpp:26,
                 from /home/ysxt001/openvino_ws/src/vision_opencv/cv_bridge/src/module_opencv4.cpp:3:
/home/ysxt001/openvino_ws/src/vision_opencv/cv_bridge/src/module.hpp: In function ‘void* do_numpy_import()’:
/usr/include/python2.7/numpy/__multiarray_api.h:1537:144: error: return-statement with no value, in function returning ‘void*’ [-fpermissive]
 #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
                                                                                                                                                ^
/usr/include/python2.7/numpy/__multiarray_api.h:1537:144: note: in definition of macro ‘import_array’
 #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
                                                                                                                                                ^~~~~~
In file included from /usr/include/python2.7/numpy/ndarrayobject.h:27:0,
                 from /home/ysxt001/openvino_ws/src/vision_opencv/cv_bridge/src/module.hpp:26,
                 from /home/ysxt001/openvino_ws/src/vision_opencv/cv_bridge/src/module.cpp:35:
/home/ysxt001/openvino_ws/src/vision_opencv/cv_bridge/src/module.hpp: In function ‘void* do_numpy_import()’:
/usr/include/python2.7/numpy/__multiarray_api.h:1537:144: error: return-statement with no value, in function returning ‘void*’ [-fpermissive]
 tring(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
                                                                     ^
/usr/include/python2.7/numpy/__multiarray_api.h:1537:144: note: in definition of macro ‘import_array’
 tring(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
                                                                     ^~~~~~
vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/build.make:86: recipe for target 'vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/module_opencv4.cpp.o' failed
make[2]: *** [vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/module_opencv4.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/build.make:62: recipe for target 'vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/module.cpp.o' failed
make[2]: *** [vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/module.cpp.o] Error 1
CMakeFiles/Makefile2:1293: recipe for target 'vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/all' failed
make[1]: *** [vision_opencv/cv_bridge/src/CMakeFiles/cv_bridge_boost.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
> Invoking "make -j12 -l12" failed

Any idea why I get this error?

**Comment by LewisLiuPub** [comment]
hi，currently, vision_opencv/cv_bridge doesn't support openCV 4.x. So the best option for you is to change openCV to 3.x in your build environment.
as an alternative, I have also filed new patch for cv_bridge project to support openCV4.x, you can also try that version, see more from cv_bridge github repo.

**Comment by HermanLiu1** [comment]
Thanks a lot! When I change the version of vision_opencv to the branch of melodic(My Ros version is melodic), Everything is ok.

**Comment by LewisLiuPub** [comment]
Glad to know that, so close this defect.
